name: Feature Request
description: Suggest a new feature or enhancement
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please provide as much detail as possible.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this to work?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you thought of other ways to solve this?

  - type: dropdown
    id: milestone
    attributes:
      label: Suggested Milestone
      options:
        - M0 - Bootstrap
        - M1 - Schema/Seed
        - M2 - Rack Map
        - M3 - Containers/QR
        - M4 - Items/Photos
        - M5 - History/Search
        - M6 - PWA/Deploy
        - Future

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Mockups, examples, or other context
